# -*- coding: utf-8 -*-
"""Langchain Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eeJWF5949gVFpR15VxCNfSwdArj99EOW
"""

!pip install -q -U langchain-community langchain-groq

import os           # saves API key to the env variable
from langchain_groq import ChatGroq

os.environ["GROQ_API_KEY"] = ""

# langchain gives you readymade prompt templates for user prompt
# we get the user's messsage and the systems message. LLM acts as a chatbot so we will send the systems message and the suer message
# those messages will be passed to this readymade chatprompt template.
# We dont have to use any prompt template here.
from langchain_core.prompts import ChatPromptTemplate

# converts raw output coming from the LLM to string output
from langchain_core.output_parsers import StrOutputParser

# We have the Chatgroq we are going to use the grok client to connect to the opensource LLMs available in groq
from langchain_groq import ChatGroq

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.1
)

parser = StrOutputParser()  # converts raw LLM output to string output

# chathistory is a list of messages and each message will have a role and content.
# role 1. system, 2.assistant
# thsi is passed to the chat prompt template so we just have to mention the tuples here.
# we will send the entire chat history to the LLM to give it proper context.

def chat():
  chat_history = [
      ("system", "You are a helpful chatbot. Be concise and accurate")
  ]

  print("Langchain chatbot. type 'exit' to quit.\n")

  # We need a while loop to keep asking the user to enter a question.
  while True:
    user_input = input("You: ").strip()
    if user_input.lower() == 'exit':
      break;

    # add user message to the chat history for context. This is of the form role, context
    # Both the role and context should be in the form of a tuple.
    chat_history.append(("user", user_input))

    # Building the prompt dynamically
    prompt = ChatPromptTemplate.from_messages(chat_history)

    # We have a chain and this chain has 3 components. one is prompt, second is llm and  then 3rd is parser.
    # When this chain is invoked, first the prompt is built with chat history.
    # After that prompt is sent to the llm (prompt -> llm)
    # Raw Output coming from the llm is passed to the parser. Parser is the strOutpuParser created earlier
    chain = prompt | llm | parser

    # get response for user query
    # This has empty braces {} because we are not passing anything.
    # We are not passing anything because we already passed the input which is the chat history to the LLM in the previous step
    response = chain.invoke({})

    # show and save the assistant response
    print(f"Bot: {response}\n")

    chat_history.append(("assistant", response))
    print("-"*80)

chat()